import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ReactQueryClientProvider from "@/providers/QueryProvider";
import ThemeProvider from "@/providers/ThemeProvider";
import MainLayout from "@/layout";
import "./globals.css";
import BProgressProvider from "@/providers/ProgressProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-slate-950`}
        >
          <BProgressProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <MainLayout>
                {children}
              </MainLayout>
            </ThemeProvider>
          </BProgressProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
